mission7/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission7.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket { get; set; }

        public CartSummaryViewComponent(Basket cartService)
        {
            basket = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }

    }
}

mission7/Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission7.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["Category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

mission7/Views/Shared/ProjectSummary.cshtml
@{
}

@model Book

<!--Style with bootstrap-->
<div class="card card-outline-primary m-1 p-1">

    <!--Title-->
    <div class="bg-light p-1">
        <h5>Title: @Model.Title</h5>

        <!--Price-->
        <span class="badge bg-info" style="float:right">
            Buy Now: $@Model.Price
        </span>

    </div>

    <!--List of remaining categories-->
    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn Served</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Number of Pages: @Model.PageCount</li>
    </ul>

<form method="post" asp-page="/Purchase">
    <input type="hidden" asp-for="@Model.BookId" />
    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

    <span class="card-text">
        <button type="submit" class="btn btn-success btn-sm float-right">Purchase</button>
    </span>
</form>

</div>

mission7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mission7</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Online Bookstore</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <!--<div class="bg-dark text-light p-2">
        <span class="navbar-brand m-lg-2">Online Bookstore</span>
    </div> -->

    <div class="row m-1 p-1">

        <div id="types" class="col-4">
            <vc:types></vc:types>
        </div>

        <div class="col-8">
            <div>
                @RenderBody()
            </div>
        </div>

    </div>

</body>
</html>