mission7/Models/Purchase.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace mission7.Models
{
    public class Purchase
    {
        [Key]
        [BindNever]
        public int PurchaseId { get; set; }

        [BindNever]
        public ICollection<BasketLineItem> Lines { get; set; }

        [Required(ErrorMessage = "Please enter a name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter the first address line")]
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        
        [Required(ErrorMessage = "Please enter a city name")]
        public string City { get; set; }
        
        [Required(ErrorMessage = "Please enter a state")]
        public string State { get; set; }
        public string Zip { get; set; }
        
        [Required(ErrorMessage = "Please enter a country")]
        public string Country { get; set; }

        [BindNever]
        public bool PurchaseReceived { get; set; }
    }
}

mission7/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using mission7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission7.Controllers
{
    public class PurchaseController : Controller
    {

        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }

        public PurchaseController(IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }


    }
}

mission7/Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using mission7.Infrastructure;
using mission7.Models;

namespace mission7.Pages
{
    public class PurchaseModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        public PurchaseModel(IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1, (float)b.Price);

            return RedirectToPage(new { ReturnUrl = returnUrl });

        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

mission7/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mission7.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mission7/Pages/Purchase.cshtml
@page
@model mission7.Pages.PurchaseModel
@{
}

<h2>Your Cart:</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@((i.Price).ToString("c"))</td>
                <td>@((i.Quantity * i.Price).ToString("c"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId"/>
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>

            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Purchase">Checkout</a>
</div>

mission7/Pages/PurchaseCompleted.cshtml
@page
@model mission7.Pages.PurchaseCompletedModel
@{
}

<div class="text-center">
    <h2>Thanks! Your order has been processed! </h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

mission7/Pages/_PurchaseLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        Online Bookstore
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>